### PR TITLE
Laravel 7 support

### LINKED ISSUE #122: Laravel 7 support

### PR DESCRIPTION
**Pull request by olegmelnik**
Resolves #122

### CODE REVIEW

**Comment by mstaack** [comment]
@njbarrett please consider tagging a new L7 release when you have time 👍

**Comment by njbarrett** [comment]
Thanks @olegmelnik !

**Comment by olegmelnik** [comment]
https://github.com/bosnadev/database/pull/39

@njbarrett bosnadev/database also need to update

**Comment by mstaack** [comment]
waiting for bosnadevs repo to be updated, then will do a fresh release hopefully :)

**Pull request merged**
